//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caddie.Golfbox {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://golfbox.net/web/services/webservice/group", ConfigurationName="Golfbox.Group")]
    public interface Group {
        
        // CODEGEN: Generating message contract since message SetGroupRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://golfbox.net/web/services/webservice/SetGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Caddie.Golfbox.SetGroupResponse SetGroup(Caddie.Golfbox.SetGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://golfbox.net/web/services/webservice/SetGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<Caddie.Golfbox.SetGroupResponse> SetGroupAsync(Caddie.Golfbox.SetGroupRequest request);
        
        // CODEGEN: Generating message contract since message GetGroupNamesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://golfbox.net/web/services/webservice/GetGroupNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Caddie.Golfbox.GetGroupNamesResponse GetGroupNames(Caddie.Golfbox.GetGroupNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://golfbox.net/web/services/webservice/GetGroupNames", ReplyAction="*")]
        System.Threading.Tasks.Task<Caddie.Golfbox.GetGroupNamesResponse> GetGroupNamesAsync(Caddie.Golfbox.GetGroupNamesRequest request);
        
        // CODEGEN: Generating message contract since message GetGroupMembersRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://golfbox.net/web/services/webservice/GetGroupMembers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Caddie.Golfbox.GetGroupMembersResponse GetGroupMembers(Caddie.Golfbox.GetGroupMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://golfbox.net/web/services/webservice/GetGroupMembers", ReplyAction="*")]
        System.Threading.Tasks.Task<Caddie.Golfbox.GetGroupMembersResponse> GetGroupMembersAsync(Caddie.Golfbox.GetGroupMembersRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://golfbox.net/web/services/webservice")]
    public partial class UserCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountField;
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://golfbox.net/web/services/webservice/group")]
    public partial class GroupMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string handicapField;
        
        private string emailField;
        
        private string sexField;
        
        private System.DateTime birthdayField;
        
        private string memberNumberField;
        
        private System.DateTime handicapDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Handicap {
            get {
                return this.handicapField;
            }
            set {
                this.handicapField = value;
                this.RaisePropertyChanged("Handicap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("Birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MemberNumber {
            get {
                return this.memberNumberField;
            }
            set {
                this.memberNumberField = value;
                this.RaisePropertyChanged("MemberNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime HandicapDate {
            get {
                return this.handicapDateField;
            }
            set {
                this.handicapDateField = value;
                this.RaisePropertyChanged("HandicapDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://golfbox.net/web/services/webservice/group")]
    public partial class GroupNameItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GroupMember[] membersField;
        
        private string nameField;
        
        private System.Guid gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public GroupMember[] Members {
            get {
                return this.membersField;
            }
            set {
                this.membersField = value;
                this.RaisePropertyChanged("Members");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://golfbox.net/web/services/webservice/group")]
    public partial class GroupNameList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GroupNameItem[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public GroupNameItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetGroup", WrapperNamespace="http://golfbox.net/web/services/webservice/group", IsWrapped=true)]
    public partial class SetGroupRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://golfbox.net/web/services/webservice")]
        public Caddie.Golfbox.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://golfbox.net/web/services/webservice/group", Order=0)]
        public System.Xml.XmlNode GroupXML;
        
        public SetGroupRequest() {
        }
        
        public SetGroupRequest(Caddie.Golfbox.UserCredentials UserCredentials, System.Xml.XmlNode GroupXML) {
            this.UserCredentials = UserCredentials;
            this.GroupXML = GroupXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetGroupResponse", WrapperNamespace="http://golfbox.net/web/services/webservice/group", IsWrapped=true)]
    public partial class SetGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://golfbox.net/web/services/webservice/group", Order=0)]
        public System.Xml.XmlNode SetGroupResult;
        
        public SetGroupResponse() {
        }
        
        public SetGroupResponse(System.Xml.XmlNode SetGroupResult) {
            this.SetGroupResult = SetGroupResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://golfbox.net/web/services/webservice/group")]
    public enum GroupType {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Static,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Dynamic,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGroupNames", WrapperNamespace="http://golfbox.net/web/services/webservice/group", IsWrapped=true)]
    public partial class GetGroupNamesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://golfbox.net/web/services/webservice")]
        public Caddie.Golfbox.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://golfbox.net/web/services/webservice/group", Order=0)]
        public Caddie.Golfbox.GroupType GroupType;
        
        public GetGroupNamesRequest() {
        }
        
        public GetGroupNamesRequest(Caddie.Golfbox.UserCredentials UserCredentials, Caddie.Golfbox.GroupType GroupType) {
            this.UserCredentials = UserCredentials;
            this.GroupType = GroupType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGroupNamesResponse", WrapperNamespace="http://golfbox.net/web/services/webservice/group", IsWrapped=true)]
    public partial class GetGroupNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://golfbox.net/web/services/webservice/group", Order=0)]
        public Caddie.Golfbox.GroupNameList GetGroupNamesResult;
        
        public GetGroupNamesResponse() {
        }
        
        public GetGroupNamesResponse(Caddie.Golfbox.GroupNameList GetGroupNamesResult) {
            this.GetGroupNamesResult = GetGroupNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGroupMembers", WrapperNamespace="http://golfbox.net/web/services/webservice/group", IsWrapped=true)]
    public partial class GetGroupMembersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://golfbox.net/web/services/webservice")]
        public Caddie.Golfbox.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://golfbox.net/web/services/webservice/group", Order=0)]
        public System.Guid GroupGUID;
        
        public GetGroupMembersRequest() {
        }
        
        public GetGroupMembersRequest(Caddie.Golfbox.UserCredentials UserCredentials, System.Guid GroupGUID) {
            this.UserCredentials = UserCredentials;
            this.GroupGUID = GroupGUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGroupMembersResponse", WrapperNamespace="http://golfbox.net/web/services/webservice/group", IsWrapped=true)]
    public partial class GetGroupMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://golfbox.net/web/services/webservice/group", Order=0)]
        public Caddie.Golfbox.GroupNameList GetGroupMembersResult;
        
        public GetGroupMembersResponse() {
        }
        
        public GetGroupMembersResponse(Caddie.Golfbox.GroupNameList GetGroupMembersResult) {
            this.GetGroupMembersResult = GetGroupMembersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroupChannel : Caddie.Golfbox.Group, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupClient : System.ServiceModel.ClientBase<Caddie.Golfbox.Group>, Caddie.Golfbox.Group {
        
        public GroupClient() {
        }
        
        public GroupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caddie.Golfbox.SetGroupResponse Caddie.Golfbox.Group.SetGroup(Caddie.Golfbox.SetGroupRequest request) {
            return base.Channel.SetGroup(request);
        }
        
        public System.Xml.XmlNode SetGroup(Caddie.Golfbox.UserCredentials UserCredentials, System.Xml.XmlNode GroupXML) {
            Caddie.Golfbox.SetGroupRequest inValue = new Caddie.Golfbox.SetGroupRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.GroupXML = GroupXML;
            Caddie.Golfbox.SetGroupResponse retVal = ((Caddie.Golfbox.Group)(this)).SetGroup(inValue);
            return retVal.SetGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caddie.Golfbox.SetGroupResponse> Caddie.Golfbox.Group.SetGroupAsync(Caddie.Golfbox.SetGroupRequest request) {
            return base.Channel.SetGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caddie.Golfbox.SetGroupResponse> SetGroupAsync(Caddie.Golfbox.UserCredentials UserCredentials, System.Xml.XmlNode GroupXML) {
            Caddie.Golfbox.SetGroupRequest inValue = new Caddie.Golfbox.SetGroupRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.GroupXML = GroupXML;
            return ((Caddie.Golfbox.Group)(this)).SetGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caddie.Golfbox.GetGroupNamesResponse Caddie.Golfbox.Group.GetGroupNames(Caddie.Golfbox.GetGroupNamesRequest request) {
            return base.Channel.GetGroupNames(request);
        }
        
        public Caddie.Golfbox.GroupNameList GetGroupNames(Caddie.Golfbox.UserCredentials UserCredentials, Caddie.Golfbox.GroupType GroupType) {
            Caddie.Golfbox.GetGroupNamesRequest inValue = new Caddie.Golfbox.GetGroupNamesRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.GroupType = GroupType;
            Caddie.Golfbox.GetGroupNamesResponse retVal = ((Caddie.Golfbox.Group)(this)).GetGroupNames(inValue);
            return retVal.GetGroupNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caddie.Golfbox.GetGroupNamesResponse> Caddie.Golfbox.Group.GetGroupNamesAsync(Caddie.Golfbox.GetGroupNamesRequest request) {
            return base.Channel.GetGroupNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caddie.Golfbox.GetGroupNamesResponse> GetGroupNamesAsync(Caddie.Golfbox.UserCredentials UserCredentials, Caddie.Golfbox.GroupType GroupType) {
            Caddie.Golfbox.GetGroupNamesRequest inValue = new Caddie.Golfbox.GetGroupNamesRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.GroupType = GroupType;
            return ((Caddie.Golfbox.Group)(this)).GetGroupNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caddie.Golfbox.GetGroupMembersResponse Caddie.Golfbox.Group.GetGroupMembers(Caddie.Golfbox.GetGroupMembersRequest request) {
            return base.Channel.GetGroupMembers(request);
        }
        
        public Caddie.Golfbox.GroupNameList GetGroupMembers(Caddie.Golfbox.UserCredentials UserCredentials, System.Guid GroupGUID) {
            Caddie.Golfbox.GetGroupMembersRequest inValue = new Caddie.Golfbox.GetGroupMembersRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.GroupGUID = GroupGUID;
            Caddie.Golfbox.GetGroupMembersResponse retVal = ((Caddie.Golfbox.Group)(this)).GetGroupMembers(inValue);
            return retVal.GetGroupMembersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caddie.Golfbox.GetGroupMembersResponse> Caddie.Golfbox.Group.GetGroupMembersAsync(Caddie.Golfbox.GetGroupMembersRequest request) {
            return base.Channel.GetGroupMembersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caddie.Golfbox.GetGroupMembersResponse> GetGroupMembersAsync(Caddie.Golfbox.UserCredentials UserCredentials, System.Guid GroupGUID) {
            Caddie.Golfbox.GetGroupMembersRequest inValue = new Caddie.Golfbox.GetGroupMembersRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.GroupGUID = GroupGUID;
            return ((Caddie.Golfbox.Group)(this)).GetGroupMembersAsync(inValue);
        }
    }
}
